### ISSUE TITLE
How to implement these carto css in mapnik c++

### ISSUE THREAD

**Issue by am2222** [rinigus/mapnik-styles-sqlite#8]
Hi,
can you please give me a hint about using these carto css files in mapnik?should I convert them into mapnik xml map?

**Comment by rinigus** [comment]
Hi,

you would need to convert them into XML using `carto`. In practice, if you have carto installed and in the path, its sufficient to run `make.py` from the root of this project.

Generated XML is actually available as a part of OSM Scout Server at https://github.com/rinigus/osmscout-server/tree/master/mapnik .

Note that there are two steps required: you need SQLite database that has the structure and data in accordance to the used styles and the styles. 

To import the data, get corresponding PBF and run https://github.com/rinigus/mapnik-styles-sqlite/blob/master/importer/import_pbf.sh . You would need `org2ogr` and `spatialite` installed as well as `wkb2twkb` compiled to get compressed geometries in TWKB format (significant reduction in storage). 

`wkb2twkb` can be installed by running https://github.com/rinigus/mapnik-styles-sqlite/blob/master/importer/install_twkb.sh in import subfolder of this repository.

Please note that you need Mapnik with the support for TWKB in SQLite. For that you can either use Mapnik master branch or patch 3.0.15 as done in https://github.com/rinigus/pkg-mapnik . 

If you wish to use regular WKB format (about 2 times larger files, if I remember correctly), please adjust 

```
config["sqlite"]["wkb_format"] = "twkb"
```

in `configure.py` and import scripts.

Good luck and let me know how it went.

**Comment by am2222** [comment]
@rinigus wow thanks very much for your detailed answer, I'll let you know the results. thanks very much

**Comment by am2222** [comment]
@rinigus Hi,
I have edited sqlite to support TWKB, and I am working on other parts, I faced a question. Does these styles supports almost everything just like osm?or it is just for some landmarks?

**Comment by rinigus** [comment]
Hi, these styles are used as a general styles with the POIs shown, as I thought would of interest. You can alter them to adjust to your needs. For that, you would need to adjust import (if POI/feature is not imported) and the style to show it.

Note that SQLite (by itself) does not know anything about TWKB. Its Mapnik that has to be ready for it.

**Comment by am2222** [comment]
@rinigus  well, I think to import I have to edit osmconfig file which is used by ogr2ogr, shouldn't I? Yes As far as I have found we just define  some flags to read geom from BLOB data which are in TWKB format in mapnik, I was wondering if we query data based on BBOX in sqlite input plugin but I have no idea if it improves preformance or not,
Also have you tried to read from pbf files directly into mapnik?It seems as they are linear files it will not show any good performance.

**Comment by rinigus** [comment]
Well, I would suggest to get it running first with the current configs.

To change POIs, you would have to change osmconfig, reorganize.sql, and style files including spatialite.mml. 

These SQLite files have R*Tree index and Mapnik uses. Didn't tried PBF directly.

**Comment by am2222** [comment]
@rinigus thank very much for your answer.

**Comment by am2222** [comment]
@rinigus  Hi,
I successfully configured mapnik to use TWKB and generated a database from my pbf file, Now to use them I have to add a datasource to mapnik map, then which styles xml should I import to my map? I am a little confused by this.

**Comment by rinigus** [comment]
Hi,

you can take any style you like. For start, take the default/day, as in https://github.com/rinigus/osmscout-server/tree/master/mapnik/default/day

As an example of Mapnik usage, you could look into https://github.com/rinigus/osmscout-server/blob/master/src/mapnikmaster.cpp

**Comment by am2222** [comment]
@rinigus wow thanks very much for the links

**Comment by rinigus** [comment]
Closing it, but you could still ask the questions if needed.

**Comment by am2222** [comment]
@rinigus  Hi, While I was rendering maps I found some layers which it seems they are grid lines, can you please help me find them?I don't know their name, I want to change their color

**Comment by rinigus** [comment]
I have no idea what could cause such grid lines in the maps, Are you sure its not rendering problem of the maps and you don't see tile borders?

**Comment by am2222** [comment]
@rinigus well I am not sure, they could be tile borders as they are the same color as map background and they change based on map tiles, What could make this problem?

**Comment by rinigus** [comment]
that I don't know, sorry

**Comment by am2222** [comment]
@rinigus thanks very much
